// Auto-generated by astro-js-typesafe-routes. Do not edit.

declare module "astro-js-typesafe-routes/path" {
  export type Routes = {
    "/": { params: null };
  };

  export type RouteId = keyof Routes;

  export type ParamsRecord<T extends RouteId> =
    Routes[T]["params"] extends Array<string>
      ? { [K in Routes[T]["params"][number]]: string }
      : never;

  export type RouteOptions<T extends RouteId> = {
    to: T;
    locale?: string;
    search?: Record<string, string>;
    hash?: string;
  } & (Routes[T]["params"] extends null
    ? { params?: never }
    : { params: ParamsRecord<T> });

  export function $path<T extends RouteId>(args: RouteOptions<T>): string;
}

declare module "astro-js-typesafe-routes/create-route" {
  import type { AstroGlobal, GetStaticPaths } from "astro";
  import type { RouteId, RouteOptions, ParamsRecord } from "astro-js-typesafe-routes/path";

  type AstroAny = AstroGlobal<unknown, unknown, unknown>;

  export function createRoute<T extends RouteId>(opts: { routeId: T }): {
    getParams: (astro: AstroAny) => Routes[T]["params"] extends null ? never : ParamsRecord<T>;
    getProps: <P>(astro: AstroAny) => P;
    redirect: <L extends RouteId>(astro: AstroAny, link: RouteOptions<L>) => Response;
    rewrite: <L extends RouteId>(astro: AstroAny, link: RouteOptions<L>) => Promise<Response>;
    createGetStaticPaths: (fn: GetStaticPaths) => GetStaticPaths;
  };
}

declare module "astro-js-typesafe-routes/link" {
  import type { HTMLAttributes } from "astro/types";
  import type { RouteOptions, RouteId } from "astro-js-typesafe-routes/path";

  type LinkBase = Omit<HTMLAttributes<"a">, "href">;
  type ExternalProps = LinkBase & { external: true; href: string; to?: never };
  type InternalProps<T extends RouteId> = LinkBase &
    RouteOptions<T> & { external?: false; href?: never };

  export type Props<T extends RouteId> = ExternalProps | InternalProps<T>;
  export default function Link<T extends RouteId>(props: Props<T>): unknown;
}

declare module "astro-js-typesafe-routes/link-react" {
  import type { ComponentProps } from "react";
  import type { RouteOptions, RouteId } from "astro-js-typesafe-routes/path";

  type LinkBase = Omit<ComponentProps<"a">, "href">;
  type ExternalProps = LinkBase & { external: true; href: string; to?: never };
  type InternalProps<T extends RouteId> = LinkBase &
    RouteOptions<T> & { external?: false; href?: never };

  export type ReactLinkProps<T extends RouteId> = ExternalProps | InternalProps<T>;
  export default function Link<T extends RouteId>(props: ReactLinkProps<T>): unknown;
}
